name: "Run Verification Tests"
description: "Run coherency tests including bundle size analysis"

inputs:
  build-artifact:
    description: "Name of the build artifact to download"
    required: true

outputs:
  status:
    description: "Overall verification test execution status"
    value: ${{ steps.summary.outputs.status }}

  details:
    description: "Overall verification test execution details"
    value: ${{ steps.summary.outputs.details }}

  bundle-status:
    description: "Bundle test status"
    value: ${{ steps.bundle-test.outputs.status }}

  version-status:
    description: "Version consistency test status"
    value: ${{ steps.version-test.outputs.status }}

  category-status:
    description: "Category packages test status"
    value: ${{ steps.category-test.outputs.status }}

  dependencies-status:
    description: "Dependencies coherency test status"
    value: ${{ steps.dependencies-test.outputs.status }}

  bundle-sizes-status:
    description: "Bundle sizes test status"
    value: ${{ steps.bundle-sizes-test.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}
        path: build/

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run Bundle Package test
      id: bundle-test
      shell: bash
      run: |
        if npm run coherency:bundle; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Run Version Consistency test
      id: version-test
      shell: bash
      run: |
        if npm run coherency:version; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Run Category Packages test
      id: category-test
      shell: bash
      run: |
        if npm run coherency:category; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Run Dependencies Coherency test
      id: dependencies-test
      shell: bash
      run: |
        if npm run coherency:dependencies; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Run Bundle Sizes test
      id: bundle-sizes-test
      shell: bash
      run: |
        if npm run coherency:sizes; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Summary
      id: summary
      shell: bash
      run: |
        # Check if all tests passed
        if [[ "${{ steps.bundle-test.outputs.status }}" == "success" && \
              "${{ steps.version-test.outputs.status }}" == "success" && \
              "${{ steps.category-test.outputs.status }}" == "success" && \
              "${{ steps.dependencies-test.outputs.status }}" == "success" && \
              "${{ steps.bundle-sizes-test.outputs.status }}" == "success" ]]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=All coherency tests passed" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=Some coherency tests failed" >> $GITHUB_OUTPUT
          exit 1
        fi
