name: "Run Lint"
description: "Run linting checks with oxlint (assumes dependencies already installed)"

outputs:
  status:
    description: "Lint execution status"
    value: ${{ steps.lint.outputs.status }}

  details:
    description: "Lint execution details"
    value: ${{ steps.lint.outputs.details }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Run linting
      id: lint
      shell: bash
      run: |
        echo "Running linting with oxlint..."

        if npm run lint; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=No linting errors found" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=Linting errors detected" >> $GITHUB_OUTPUT
          exit 1
        fi
