/**
 * This file is part of helpers4.
 * Copyright (C) 2025 baxyz
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as fc from 'fast-check';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { safeReadJsonFile } from './safeReadJsonFile';
import { stripJsonComments } from './_stripJsonComments';

describe('safeReadJsonFile — property-based', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'helpers4-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('round-trips any JSON-serialisable value written to disk', () => {
    fc.assert(
      fc.property(fc.jsonValue(), (value) => {
        const filePath = join(dir, 'value.json');
        const json = JSON.stringify(value);
        writeFileSync(filePath, json);
        // Both sides go through JSON encoding — -0 becomes 0 in JSON (expected)
        expect(safeReadJsonFile(filePath)).toEqual(JSON.parse(json));
      }),
    );
  });

  it('always returns the fallback for content invalid under both strict JSON and JSONC', () => {
    const fallback = 'FALLBACK';
    fc.assert(
      fc.property(
        // safeReadJsonFile tolerates JSONC, so "invalid" here must mean invalid
        // even after comment/trailing-comma stripping — otherwise the (rare)
        // random string that happens to be valid JSONC would break this property.
        fc.string().filter((s) => {
          try {
            JSON.parse(stripJsonComments(s));
            return false;
          } catch {
            return true;
          }
        }),
        (invalidContent) => {
          const filePath = join(dir, 'invalid.json');
          writeFileSync(filePath, invalidContent);
          expect(safeReadJsonFile(filePath, fallback)).toBe(fallback);
        },
      ),
    );
  });

  it('parses JSONC content (comments + trailing commas) that strict JSON.parse would reject', () => {
    fc.assert(
      fc.property(
        fc.dictionary(fc.string({ minLength: 1, maxLength: 8 }), fc.jsonValue()),
        (obj) => {
          const filePath = join(dir, 'jsonc.json');
          // Wrap a valid JSON object with a line comment and a trailing comma —
          // both rejected by strict JSON.parse, both tolerated as JSONC.
          const entries = Object.entries(obj).map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)},`);
          const jsonc = `{\n  // generated by fast-check\n  ${entries.join('\n  ')}\n}`;
          writeFileSync(filePath, jsonc);
          // Compare against obj's own JSON round-trip, not obj directly — -0 becomes
          // 0 in JSON (expected, same caveat as the round-trip test above).
          expect(safeReadJsonFile(filePath)).toEqual(JSON.parse(JSON.stringify(obj)));
        },
      ),
    );
  });
});

describe('safeReadJsonFile — contract', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'helpers4-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('returns null (not undefined) when no fallback is given and the file is missing', () => {
    expect(safeReadJsonFile(join(dir, 'missing.json'))).toBeNull();
  });

  it('does not throw when the path is a directory, not a file', () => {
    expect(() => safeReadJsonFile(dir)).not.toThrow();
    expect(safeReadJsonFile(dir)).toBeNull();
  });

  it('does not throw on a nonexistent nested path', () => {
    expect(() => safeReadJsonFile(join(dir, 'nested', 'missing.json'))).not.toThrow();
  });

  it('fallback reference is returned as-is (no clone)', () => {
    const fallback = { original: true };
    const result = safeReadJsonFile(join(dir, 'missing.json'), fallback);
    expect(result).toBe(fallback);
  });
});
