name: "Run Unit Tests"
description: "Run unit tests with Vitest"

outputs:
  status:
    description: "Test execution status"
    value: ${{ steps.test.outputs.status }}

  details:
    description: "Test execution details"
    value: ${{ steps.test.outputs.details }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run unit tests
      id: test
      shell: bash
      run: |
        echo "Running unit tests with Vitest..."

        if npm run test; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=All unit tests passed" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=Unit tests failed" >> $GITHUB_OUTPUT
          exit 1
        fi
