name: "Run Unit Tests"
description: "Run unit tests with Vitest and coverage"

inputs:
  coverage:
    description: "Enable coverage reporting"
    required: false
    default: "false"

outputs:
  status:
    description: "Test execution status"
    value: ${{ steps.test.outputs.status }}

  details:
    description: "Test execution details"
    value: ${{ steps.test.outputs.details }}

  coverage-lines:
    description: "Lines coverage percentage"
    value: ${{ steps.coverage.outputs.lines }}

  coverage-branches:
    description: "Branches coverage percentage"
    value: ${{ steps.coverage.outputs.branches }}

  coverage-functions:
    description: "Functions coverage percentage"
    value: ${{ steps.coverage.outputs.functions }}

  coverage-statements:
    description: "Statements coverage percentage"
    value: ${{ steps.coverage.outputs.statements }}

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Run unit tests
      id: test
      shell: bash
      run: |
        echo "Running unit tests with Vitest..."

        if [ "${{ inputs.coverage }}" = "true" ]; then
          if pnpm test:coverage; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "details=All unit tests passed with coverage" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "details=Unit tests or coverage thresholds failed" >> $GITHUB_OUTPUT
            exit 1
          fi
        else
          if pnpm test; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "details=All unit tests passed" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "details=Unit tests failed" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi

    - name: Extract coverage data
      id: coverage
      if: inputs.coverage == 'true'
      shell: bash
      run: |
        if [ -f coverage/coverage-summary.json ]; then
          LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)
          FUNCTIONS=$(jq '.total.functions.pct' coverage/coverage-summary.json)
          STATEMENTS=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          
          echo "lines=$LINES" >> $GITHUB_OUTPUT
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT
          echo "functions=$FUNCTIONS" >> $GITHUB_OUTPUT
          echo "statements=$STATEMENTS" >> $GITHUB_OUTPUT
        else
          echo "lines=0" >> $GITHUB_OUTPUT
          echo "branches=0" >> $GITHUB_OUTPUT
          echo "functions=0" >> $GITHUB_OUTPUT
          echo "statements=0" >> $GITHUB_OUTPUT
        fi
