name: "Run TypeCheck"
description: "Run TypeScript type checking (assumes dependencies already installed)"

outputs:
  status:
    description: "TypeCheck execution status"
    value: ${{ steps.typecheck.outputs.status }}

  details:
    description: "TypeCheck execution details"
    value: ${{ steps.typecheck.outputs.details }}

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "pnpm"

    - name: Run type checking
      id: typecheck
      shell: bash
      run: |
        echo "Running TypeScript type checking..."

        if pnpm run typecheck; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=TypeScript compilation successful" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=TypeScript errors detected" >> $GITHUB_OUTPUT
          exit 1
        fi
