name: "Run Build"
description: "Build the project with Vite"

outputs:
  status:
    description: "Build execution status"
    value: ${{ steps.build.outputs.status }}

  details:
    description: "Build execution details"
    value: ${{ steps.build.outputs.details }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run build
      id: build
      shell: bash
      run: |
        echo "Building project with Vite..."

        if npm run build; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "details=Build completed successfully" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "details=Build failed" >> $GITHUB_OUTPUT
          exit 1
        fi
