name: "Version Manager"
description: "Calculate version for PR validation and upload package.json artifact"

inputs:
  artifact-name:
    description: "Name of the package.json artifact to upload"
    required: true

outputs:
  version:
    description: "Current version"
    value: ${{ steps.version.outputs.version }}

  changed:
    description: "Whether version-affecting changes detected"
    value: ${{ steps.version.outputs.changed }}

  status:
    description: "Status of version calculation"
    value: ${{ steps.version.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Calculate version for PR
      id: version
      shell: bash
      run: |
        echo "Calculating version for PR validation..."
        CURRENT_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
        echo "Current version: $CURRENT_VERSION"

        # For PR validation, check if there are version-affecting changes
        if git log --oneline HEAD...origin/main | grep -E "^[a-f0-9]+ (feat|fix|BREAKING CHANGE)" >/dev/null 2>&1; then
          echo "Version-affecting changes detected"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "No version-affecting changes detected"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT
        fi

    - name: Upload package.json artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: package.json
        retention-days: 1
